config/routes.rb
LearnRails::Application.routes.draw do
  resources :contacts, only: [:new, :create] 
  resources :visitors, only: [:new, :create] 
  root to: 'visitors#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base 
	has_no_table
	column :name, :string 
	column :email, :string 
	column :content, :string

	validates_presence_of :name 
	validates_presence_of :email 
	validates_presence_of :content 
	validates_format_of :email,
		:with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i 
	validates_length_of :content, :maximum => 500

	def update_spreadsheet
		connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
		ss = connection.spreadsheet_by_title('Learn-Rails-Example')
		if ss.nil?
			ss = connection.create_spreadsheet('Learn-Rails-Example') 
		end
		ws = ss.worksheets[0] 
		last_row = 1 + ws.num_rows 
		ws[last_row, 1] = Time.new 
		ws[last_row, 2] = self.name 
		ws[last_row, 3] = self.email 
		ws[last_row, 4] = self.content 
		ws.save
	end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	has_no_table
	column :email, :string
	validates_presence_of :email
	validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

	def subscribe
		mailchimp = Gibbon::API.new
		result = mailchimp.lists.subscribe({
			:id => ENV['MAILCHIMP_LIST_ID'], 
			:email => {:email => self.email}, 
			:double_optin => false, 
			:update_existing => true, 
			:send_welcome => true
		})
		Rails.logger.info("Subscribed #{self.email} to MailChimp") if result 
	end
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(secure_params)
		if @contact.valid?
			@contact.update_spreadsheet
			UserMailer.contact_email(@contact).deliver
			flash[:notice] = "Message sent from #{@contact.name}."
			redirect_to root_path
		else
			render :new
		end	
	end

	private

	def secure_params
		params.require(:contact).permit(:name, :email, :content)
	end	

end	

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def new
		@visitor = Visitor.new
	end

	def create
		@visitor = Visitor.new(secure_params) 
		if @visitor.valid?
			@visitor.subscribe
			flash[:notice] = "Signed up #{@visitor.email}." 
			redirect_to root_path
		else
			render :new
		end 
	end
	
	private
	
	def secure_params 
		params.require(:visitor).permit(:email)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
	<%= simple_form_for @contact do |form| %> 
		<%= form.error_notification %>
		<%= form.input :name, autofocus: true %>
		<%= form.input :email %>
		<%= form.input :content, as: :text %>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
￼<% content_for :title do %>About<% end %>
<h3>About Aniruddha Barapatre</h3>
<p>He was born in Nagpur, India. He left India for England, excelled at the University of Houston, and served in the Royal Loamshire Regiment. While in service, he invented the kanuten valve used in the processing of unobtainium for industrial use. With a partner, Granda Fairbook, he founded Acme Manufacturing, later acquired by the Advent Corporation, to develop his discovery for use in the Turboencabulator. Mr. Barapatre is now retired and lives in Middlehampton with a favorite cat, where he raises Griadium frieda and collects metasyntactic variables.</p>
<p>His favorite poem is:</p>
<p>Tiger by William Blake.</p>

app/views/visitors/new.html.erb
<% content_for :title do %>Aniruddha Barapatre<% end %>
<% content_for :description do %>Website of Aniruddha Barapatre<% end %> 
<section>
   <%= image_tag "me.jpg" %>
</section>
<section>
   	<div class="column">
    	<h2>Stay in touch.</h2>
   	</div>
   	<div class="column">
		<div class="form-centered">
			<%= simple_form_for @visitor do |f| %>
				<%= f.error_notification %>
				<%= f.input :email, label: false, :placeholder => 'Your email address...' %> <br/>
				<%= f.button :submit, "Sign up for the newsletter", :class => "submit" %>
			<% end %> 
		</div>
   </div>
 </section>